export const ORDER_STATUS = {
  ASSIGNED: "ASSIGNED",
  ARRIVED_AT_RESTAURANT: "ARRIVED_AT_RESTAURANT",
  PICKED_UP: "PICKED_UP",
  ON_THE_WAY: "ON_THE_WAY",
  ARRIVED_AT_DROP: "ARRIVED_AT_DROP",
  DELIVERED: "DELIVERED",
};
