// export const ORDER_STATUS = {
//   PICKED_UP: 'PICKED_UP',
//   ARRIVED: 'ARRIVED',
//   DELIVERED: 'DELIVERED',
// };
// orderStates.js



export const ORDER_STATUS = {
  PICKUP_ASSIGNED: 'PICKUP_ASSIGNED',
  ON_WAY_TO_PICKUP: 'ON_WAY_TO_PICKUP',
  AT_RESTAURANT: 'AT_RESTAURANT',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  ON_WAY_TO_DROP: 'ON_WAY_TO_DROP',
  QR_SCAN_REQUIRED: 'QR_SCAN_REQUIRED',
  AT_DROP: 'AT_DROP',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
};



