export const NOTIFICATION_TYPES = {
  // SLOT
  SLOT_BOOKED: 'SLOT_BOOKED',
  SLOT_START_REMINDER: 'SLOT_START_REMINDER',
  SLOT_STARTED: 'SLOT_STARTED',
  SLOT_ENDING_SOON: 'SLOT_ENDING_SOON',
  SLOT_CANCELLED_SYSTEM: 'SLOT_CANCELLED_SYSTEM',
  SLOT_MISSED: 'SLOT_MISSED',

  // EARNINGS
  EARNINGS_CREDITED: 'EARNINGS_CREDITED',
  WEEKLY_SUMMARY: 'WEEKLY_SUMMARY',
  MONTHLY_SUMMARY: 'MONTHLY_SUMMARY',
  INCENTIVE_ACHIEVED: 'INCENTIVE_ACHIEVED',
  INCENTIVE_AVAILABLE: 'INCENTIVE_AVAILABLE',

  // ORDERS
  NEW_ORDER: 'NEW_ORDER',
  ORDER_MISSED: 'ORDER_MISSED',
  PICKUP_REMINDER: 'PICKUP_REMINDER',
  DELIVERY_REMINDER: 'DELIVERY_REMINDER',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',

  // SYSTEM
  FORCE_LOGOUT: 'FORCE_LOGOUT',
};
